version: '3.8'

services:
  ego-planner:
    build:
      context: .
      dockerfile: Dockerfile
    image: ego-planner-swarm:latest
    container_name: ego-planner-swarm
    volumes:
      - .:/workspace/ego-planner-swarm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash
